# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' my k-means function
#'
#' @param x the data to be clustered
#' @param centers initial centers
#' @param maxiter the max iter
#' @param strict how strict?
#' @export
kmeans_cpp <- function(x, centers, maxiter, strict) {
    .Call(`_hospitalstars_kmeans_cpp`, x, centers, maxiter, strict)
}

